### ISSUE TITLE
代码缩进问题

### ISSUE THREAD

**Issue by lianglanzheng** [HackSwjtu/HackSwjtu-docs#3]
## 1. ```Tab```和```空格```不同
Tab的编码是```0x09```，空格的编码是```0x20```。而两者在文本编辑器都显示为空白。

## 2. 一些文本编辑器会将Tab键转换为```空格```
在默认配置下：
* Atom : 当用户按下Tab键，输入的是2个```0x20```
* Visual Studio Code : 当用户按下Tab键，输入的是4个```0x20```
* Sublime Text : 当用户按下Tab键，输入的是1个```0x09```

此外，有的文本编辑器会根据上文决定输入的是```0x09```还是```0x20```及其数量。

## 3.要解决的问题
当一个文件内同时使用```0x09```和```0x20```缩进时，在不同的文本编辑器中对齐情况是不同的。  
例子：在Visual Studio Code中对齐的代码，在Atom中使用```0x20```缩进的行会突出来。

## 4.现状
1. 截至2017年4月3日，weapp-clawjtu中的代码均使用```0x20```进行缩进。
2. 其余仓库代码大多数使用```0x20```进行缩进。
3. 存在同时使用```0x09```和```0x20```进行缩进的代码文件。

## 5.解决的方法
1. 只用```0x09```或只用```0x20```进行缩进。这种方法无论在哪个文本编辑器上阅读，代码都是对齐的。
2. 允许同时使用```0x09```和```0x20```进行缩进，但规定每个```0x09```等效2个或4个```0x20```。这种方法在配置好的文本编辑器才能正常阅读。

## 6.备注
可以用以下方法检查代码中缩进的方式：
* Atom : ```Settings > Editor > Show Invisibles```，```0x09```显示为浅色双尖头，```0x20```显示为浅色小圆点
* Visual Studio Code : ```显示 > 切换呈现空格```，```0x09```显示为浅色箭头，```0x20```显示为浅色小圆点
* Sublime Text : 选中文本，```0x09```显示为浅色横线，```0x20```显示为浅色小圆点
* 使用十六进制编辑器查看文件

**Comment by WangNianyi2001** [comment]
不然我们写个脚本自动格式化吧233
*不过这点应该不影响，wxml的容错率还是挺大的*

**Comment by lianglanzheng** [comment]
1. 自动格式化会导致git中出现多余的更改行，不方便项目维护，尤其在查错的时候
2. 并不是每个人都愿意上传前检查跑一遍脚本。脚本还要适配多个系统多个文本编辑器还是不同的git管理工具？
3. 在HTML等大多数语言中缩进不一致不是错误（对机器）。问题是缩进不一致会影响代码维护效率（对人）

**Comment by lianglanzheng** [comment]
因为当前仓库中代码大多数使用空格```0x20```缩进，包括@WangNianyi2001 提交的 js，  
所以建议规定缩进使用空格。

**Comment by WangNianyi2001** [comment]
空格不方便操作，且占用文件空间。
替换是一次性的，便于日后的管理、替换等操作。

Nianyi Wang

**Comment by lianglanzheng** [comment]
在网页前端：
* HTML
* CSS
* JavaScript

使用2个```0x20```缩进
